account_id = "496ea6f6559820c64e0b6f776d64731f"
name = "kolibri-finance"
compatibility_date = "2024-12-11"
workers_dev = true
site = { bucket = ".output/public" }

main = "workers-site/index.js"

[env.testnet]
route = "testnet.kolibri.finance/*"

[env.sandbox]
route = "sandbox.kolibri.finance/*"

[env.production]
route = "kolibri.finance/*"
